spring:
  application:
    name: linkvault-server

  datasource:
    url: jdbc:mysql://localhost:3307/linkvault?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: linkvault
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.linkvault.linkvaultserver: info

app:
  jwt:
    secret: "linkvault-dev-secret-key-linkvault-dev-secret-key"
    access-token-expires-in: 604800
  metadata:
    youtube-api-key: "AIzaSyDMUXJTmtYbhujwKwkBN3qFEdCnijJV1xE"
